# Generated by Django 3.2.3 on 2021-12-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_user_book_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
    ]
